const sources = ["March Madness Bracket Slides",
    "MLK & Malcolm X Biographies",
    "https://www.history.com/news/black-power-movement-civil-rights",
    "https://www.blackpast.org/african-american-history/montgomery-bus-boycott-1955-56/",
    "politico.com/story/2018/03/07/this-day-in-politics-march-7-1965-437394",
    "https://www.washingtonpost.com/lifestyle/style/fifty-years-after-his-death-malcolm-x-speaks-to-the-current-moment/2015/02/19/4dba5ca4-091e-4303-b3ee-6a655c583655_story.html",
    "britannica.com/biography/Martin-Luther-King-Jr",
    "https://www.nps.gov/articles/montgomery-bus-boycott.htm",
    "https://www.youtube.com/watch?v=JXi2lM7-NB8",
    "https://www.youtube.com/watch?v=6x0l_vkjozc",
    "https://www.youtube.com/watch?v=FE6Yvy--5aw",
    "https://www.smithsonianmag.com/smithsonian-institution/courage-at-the-greensboro-lunch-counter-4507661/",
    "https://www.youtube.com/watch?v=Qfo7rN7Alu4",
    "https://www.dol.gov/agencies/oasam/civil-rights-center/statutes/civil-rights-act-of-1964",
    "https://www.youtube.com/watch?v=vP4iY1TtS3s",
    "https://www.youtube.com/watch?v=ML3WaEsCB98",
    "https://www.youtube.com/watch?v=ifH5X9dYzG8",
    "https://www.youtube.com/watch?v=Vd6D64Ai49I",
    "https://www.history.com/topics/1960s/watts-riots",
    "https://www.blackpast.org/african-american-history/events-african-american-history/james-merediths-march-against-fear-1966/",
    "https://www.britannica.com/topic/Fair-Housing-Act",
    "https://www.youtube.com/watch?v=waxW-R_fFSQ",
    "https://www.youtube.com/watch?v=Gj89PEVUM88"
]

export default sources